<?php

namespace AppBundle\Repository;

/**
 * BackerGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackerGradeRepository extends \Doctrine\ORM\EntityRepository
{
}
