<?php

namespace AppBundle\Repository;

/**
 * BackerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackerRepository extends \Doctrine\ORM\EntityRepository
{
}
