<?php

namespace AppBundle\Repository;

/**
 * CoreTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoreTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
