<?php

namespace AppBundle\Repository;

/**
 * CustomerProfilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerProfilesRepository extends \Doctrine\ORM\EntityRepository
{
}
