<?php

namespace AppBundle\Repository;

/**
 * CustomerContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerContactsRepository extends \Doctrine\ORM\EntityRepository
{
}
