<?php

namespace AppBundle\Repository;

/**
 * DeliveryChargeRatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryChargeRatesRepository extends \Doctrine\ORM\EntityRepository
{
}
