<?php

namespace AppBundle\Repository;

/**
 * DoorCalculatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoorCalculatorRepository extends \Doctrine\ORM\EntityRepository
{
}
