<?php

namespace AppBundle\Repository;

/**
 * DoorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoorsRepository extends \Doctrine\ORM\EntityRepository
{
}
