<?php

namespace AppBundle\Repository;

/**
 * EdgeFinishSpeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdgeFinishSpeciesRepository extends \Doctrine\ORM\EntityRepository
{
}
