<?php

namespace AppBundle\Repository;

/**
 * EdgeFinishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdgeFinishRepository extends \Doctrine\ORM\EntityRepository
{
}
