<?php

namespace AppBundle\Repository;

/**
 * FaceGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaceGradeRepository extends \Doctrine\ORM\EntityRepository
{
}
