<?php

namespace AppBundle\Repository;

/**
 * FlakexFiguredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlakexFiguredRepository extends \Doctrine\ORM\EntityRepository
{
}
