<?php

namespace AppBundle\Repository;

/**
 * GrainDirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrainDirectionRepository extends \Doctrine\ORM\EntityRepository
{
}
