<?php

namespace AppBundle\Repository;

/**
 * LineItemStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineItemStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
