<?php

namespace AppBundle\Repository;

/**
 * MessageTemplatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTemplatesRepository extends \Doctrine\ORM\EntityRepository
{
}
