<?php

namespace AppBundle\Repository;

/**
 * OrderHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
