<?php

namespace AppBundle\Repository;

/**
 * PatternRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatternRepository extends \Doctrine\ORM\EntityRepository
{
}
