<?php

namespace AppBundle\Repository;

/**
 * PlywoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlywoodRepository extends \Doctrine\ORM\EntityRepository
{
}
