<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{

    public function getVendor($id)
    {

        $qb = $this->createQueryBuilder('p');
        $qb->select(
           'p.id profileId', 'vp.id vprofileId','p.userId','p.company','p.fname','p.lname','p.email','p.phone','p.address','p.stateId','p.city','p.zip','vp.termId','vp.comment'
        )->leftJoin(
            'AppBundle:VendorProfile',
            'vp',
            Join::WITH,
            $qb->expr()->eq('p.userId', 'vp.userId')
        )->where('p.userId=:userid')
            ->setParameter('userid',$id);

        try {
            return $qb->getQuery()->getOneOrNullResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            throw new NoResultException("No record found");
           // return null;
        }




    }

}
