<?php

namespace AppBundle\Repository;

/**
 * QuotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotesRepository extends \Doctrine\ORM\EntityRepository
{
}
