<?php

namespace AppBundle\Repository;

/**
 * QuoteStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
