<?php

namespace AppBundle\Repository;

/**
 * RoleModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
