<?php

namespace AppBundle\Repository;

/**
 * SameOnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SameOnRepository extends \Doctrine\ORM\EntityRepository
{
}
