<?php

namespace AppBundle\Repository;

/**
 * SheenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheenRepository extends \Doctrine\ORM\EntityRepository
{
}
