<?php

namespace AppBundle\Repository;

/**
 * ShippedQuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippedQuantityRepository extends \Doctrine\ORM\EntityRepository
{
}
