<?php

namespace AppBundle\Repository;

/**
 * ShippingMethodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingMethodsRepository extends \Doctrine\ORM\EntityRepository
{
}
