<?php

namespace AppBundle\Repository;

/**
 * SizeEdgeMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeEdgeMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
