<?php

namespace AppBundle\Repository;

/**
 * SkinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkinsRepository extends \Doctrine\ORM\EntityRepository
{
}
