<?php

namespace AppBundle\Repository;

/**
 * SubspeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubspeciesRepository extends \Doctrine\ORM\EntityRepository
{
}
