<?php

namespace AppBundle\Repository;

/**
 * TermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermsRepository extends \Doctrine\ORM\EntityRepository
{
}
