<?php

namespace AppBundle\Repository;

/**
 * ThicknessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThicknessRepository extends \Doctrine\ORM\EntityRepository
{
}
