<?php

namespace AppBundle\Repository;

/**
 * UnitMeasureCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitMeasureCostRepository extends \Doctrine\ORM\EntityRepository
{
}
