<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUser($username)
    {
        $result =  $this->createQueryBuilder('users')
            ->andWhere('users.username=:username')
            ->andWhere('users.isActive = :isActive')
            ->setParameter('isActive', 1)
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult();
        return $result;
    }
}
