<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUser($username)
    {
        $result =  $this->createQueryBuilder('users')
            ->andWhere('users.username=:username')
            ->andWhere('users.isActive = :isActive')
            ->setParameter('isActive', 1)
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult();
        return $result;
    }

    public function checkUser($username){
       // SELECT p.id profile_id,u.id user_id FROM profiles p LEFT JOIN users u ON p.user_id = u.id WHERE u.username = 'rajesh@gmail.com' OR p.email = 'rajesh@gmail.com'
    }
}
