<?php

namespace AppBundle\Repository;

/**
 * UvCuredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UvCuredRepository extends \Doctrine\ORM\EntityRepository
{
}
