<?php

namespace AppBundle\Repository;

/**
 * UvCuredColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UvCuredColorRepository extends \Doctrine\ORM\EntityRepository
{
}
