<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * VendorProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorProfileRepository extends \Doctrine\ORM\EntityRepository
{


    public function __constructor(){

    }
 





}
