<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * VendorProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorProfileRepository extends \Doctrine\ORM\EntityRepository
{

    private  $_rsm;
    public function __constructor(){
    $this->_rsm = new ResultSetMapping();
    }
    public function getVendors()
    {

        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p.company,p.phone,p.userId FROM AppBundle:Profile p');
        try {
            return $query->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY); // array of User objects
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }

}
