<?php

namespace AppBundle\Repository;

/**
 * VeneerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeneerRepository extends \Doctrine\ORM\EntityRepository
{
}
